# 1. Tomcat Server Setting
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12  # 인증서 파일 경로 <- keystore.p12를
    # src/main/resources밑에 뒀다면 경로 수정 X
    key-store-password: 111111  # 인증서 생성 시 설정한 비밀번호
    key-store-type: PKCS12  # 인증서 형식
  servlet:
    encoding:
      charset: UTF-8
      force: true
  address: 0.0.0.0

# 2. SpringBoot Environment Setting
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/smhs?characterEncoding=utf8
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/smdb?characterEncoding=utf8
    username: smuser
    password: 111111

# 3. Mybatis Setting
mybatis:
  type-aliases-package: edu.sm.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
# 4. Logging Setting
logging:
  level:
    root: info
  #  error > info > debug

# 5. Application Environment Setting
app:
  url:
    server_url: https://127.0.0.1:8443
  dir:
    imgdir: file:///c:/CoMong_Project/imgs/
    imgmypage: C:/CoMong_Project/doctor/src/main/resources/static/img
    uploadimgdir: c:/CoMong_Project/imgs/
    # logdir: /root/users/project/logs
    logdir: file:///c:/CoMong_Project/logs/
    readlogdir: c:/CoMong_Project/logs/
  key:
    algo: PBEWithMD5AndDES
    skey: mykey